# -*- coding: utf-8 -*-
"""aStarGame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Gn4zJNEjkyhHZCEBhx0niTsUw3sutVV
"""

def check(board):
  wins=[
      (0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)
  ]

  for i,j,k in wins:
    if board[i]==board[j]==board[k]!='':
      return board[i]
  return None

def heuristic(board):
  if check(board)=='X':
    return -10
  elif check(board)=='O':
    return 10
  return 0

def aStar(board):
  open=[]

  for i in range(9):
    if board[i]=='':
      new_board=board.copy()
      new_board[i]='X'

      g=1
      h=heuristic(new_board)
      f=g+h

      open.append((f,i))

  open.sort()

  return open[0][1]

board=[
    'X','','O',
    'X','O','',
    '','',''
]

print("Next best move for X: ")
print(aStar(board))