# -*- coding: utf-8 -*-
"""aStar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6Tz39_U3E8XXAOnxTBQkbK9HM_7zYQA
"""

def aStar(graph, heuristic, start, goal):

    open = [start]
    closed = []

    gcost = {node: float('inf') for node in graph}
    gcost[start] = 0

    parent = {start: None}

    while open:

        curr = open[0]

        # Find node with minimum f(n)=g(n)+h(n)
        for node in open:
            if gcost[node] + heuristic[node] < gcost[curr] + heuristic[curr]:
                curr = node

        # Goal found
        if curr == goal:
            path = []

            while curr is not None:
                path.append(curr)
                curr = parent[curr]

            path.reverse()
            return path

        open.remove(curr)
        closed.append(curr)

        # Check neighbors
        for neighbor, cost in graph[curr].items():

            # Skip if already visited
            if neighbor in closed:
                continue

            newg = gcost[curr] + cost

            if neighbor not in open:
                open.append(neighbor)

            elif newg >= gcost[neighbor]:
                continue

            parent[neighbor] = curr
            gcost[neighbor] = newg

    return None

graph={
    'A':{'B':2,'C':1},
    'B':{'D':3,'E':4},
    'C':{'F':5},
    'D':{},
    'E':{},
    'F':{}
}

heuristic={
    'A':10,
    'B':8,
    'C':5,
    'D':7,
    'E':3,
    'F':0
}

start='A'
goal='F'

path=aStar(graph,heuristic,start,goal)
print(path)

def aStar(graph,h,start,goal):
  open=[start]
  closed=[]

  gcost={node:float('inf') for node in graph}
  gcost[start]=0
  parent={start:None}

  while open:
    curr=open[0]

    for node in open:

      if gcost[node]+h[node]<gcost[curr]+h[curr]:
        curr=node

    if curr==goal:
      path=[]
      while curr is not None:
        path.append(curr)
        curr=parent[curr]
      path.reverse()
      return path

    open.remove(curr)
    closed.append(curr)

    for neighbor, cost in graph[curr].items():
      if neighbor in closed:
        continue

      newg=gcost[curr]+cost

      if neighbor not in open:
        open.append(neighbor)
      elif newg>=gcost[neighbor]:
        continue

      parent[neighbor]=curr
      gcost[neighbor]=newg

  return None