# -*- coding: utf-8 -*-
"""Dijkstra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUQqBx481s8ROSVZfDS0P3_ob5bKmZtk
"""

graph={
    'A':{'B':2,'C':4},
    'B':{'A':2,'C':1,'D':12},
    'C':{'A':4,'B':1,'D':2},
    'D':{'B':12,'C':2}
}

dist={
    'A':0,
    'B':float('inf'),
    'C':float('inf'),
    'D':float('inf')
}
visited=[]


while len(visited)<len(graph):

  minNode=None
  for node in graph:
    if node not in visited:
      if minNode is None or dist[node]<dist[minNode]:
        minNode=node

  visited.append(minNode)

  for neighbor,cost in graph[minNode].items():
    if dist[minNode]+cost<dist[neighbor]:
      dist[neighbor]=dist[minNode]+cost

print("Shortest Path from A: ")
for node in dist:
  print(f"{node} = {dist[node]}")