# -*- coding: utf-8 -*-
"""Kruskal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9l5LEE1RO8NClY3mBo5leqemf0sSmm_
"""

def find(parent,x):
  while parent[x]!=x:
    x=parent[x]
  return x

def kruskal(edges,vertices):
  edges.sort(key=lambda x:x[2])

  mst=[]
  cost=0
  parent={v:v for v in vertices}

  for u,v,w in edges:
    pu=find(parent,u)
    pv=find(parent,v)

    if pu!=pv:
      parent[pu]=pv
      mst.append((u,v,w))
      cost=cost+w

  print("MST: ")
  for u,v,w in mst:
    print(u,"-",v,"=",w)

  print("Total Cost: ",cost)

edges = [
    ('1', '2', 2),
    ('1', '4', 1),
    ('1', '5', 4),
    ('2', '3', 3),
    ('2', '4', 3),
    ('2', '6', 7),
    ('3', '4', 5),
    ('3', '6', 8),
    ('4', '5', 9)
]

vertices = ['1', '2', '3', '4', '5', '6']

kruskal(edges, vertices)

def find(parent,x):
  while parent[x]!=x:
    x=parent[x]
  return x

def kruskal(edges,vertices):
  edges.sort(key=lambda x:x[2])
  mst=[]
  cost=0

  parent={v: v for v in vertices}

  for u,v,w in edges:

    pu=find(parent,u)
    pv=find(parent,v)

    if pu!=pv:
      parent[pu]=pv
      mst.append((u,v,w))
      cost+=w

  print("MST: ")
  for u,v,w in mst:
    print(u,"-",v,"=",w)

  print("Total Cost: ",cost)