# -*- coding: utf-8 -*-
"""nQueens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZxbqTrj2PP2ihpD1CKX_kERLFLmY23c
"""

def solveNQueens(n):
  board=[-1]*n

  sols=[]

  col=[False]*n
  diag1=[False]*(2*n-1)
  diag2=[False]*(2*n-1)

  def isSafe(row,c):
    return not col[c] and not diag1[row+c] and not diag2[row-c+n-1]

  def solve(row):
    if row==n:
      sols.append(board.copy())

    for c in range(n):
      if isSafe(row,c):
        board[row]=c

        col[c]=True
        diag1[row+c]=True
        diag2[row-c+n-1]=True

        solve(row+1)

        col[c]=False
        diag1[row+c]=False
        diag2[row-c+n-1]=False

  solve(0)
  return sols

def printBoard(soln):
  n=len(soln)

  for i in range(n):
    row=['.']*n
    row[soln[i]]='Q'
    print(" ".join(row))
  print()

n=int(input("Enter value of N: "))
sols=solveNQueens(n)

print(f"Total Solutions: {len(sols)}")
for i,sol in enumerate(sols):
  print(f"Solution {i}: {sol}")
  printBoard(sol)