# -*- coding: utf-8 -*-
"""Prims.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1hiyGuXxhdrjfmWq-T6Zu7t52wFIc38
"""

def prim(graph,start):
  visited=[start]
  cost=0
  edges=[]

  while len(visited) < len(graph):

    min_edge=None
    min_cost=float('inf')

    for u in visited:
      for v,w in graph[u]:
        if v not in visited  and w<min_cost:
          min_cost=w
          min_edge=(u,v)

    u,v=min_edge
    visited.append(v)
    edges.append((u,v,min_cost))
    cost+=min_cost

  print("MST: ")
  for u,v,w in edges:
    print(f"{u}-{w}={v}")
  print("Total cost: ",cost)

graph = {
    '1': [('2', 2), ('4', 1),('5',4)],
    '2': [('1', 2), ('3', 3), ('4', 3),('6',7)],
    '3': [('2', 3), ('4', 5), ('6', 8)],
    '4': [('1', 1), ('2', 3),('3',5),('5',9)],
    '5': [('1', 4), ('4', 9)],
    '6': [('2', 7), ('3', 8)]
}

prim(graph,'1')

def prim(graph,start):
  visited=[start]
  edges=[]
  cost=0

  while len(visited)<len(graph):
    minEdge=None
    minCost=float('inf')

    for u in visited:
      for v,w in graph[u]:
        if v not in visited and w<minCost:
          minCost=w
          minEdge=(u,v)

    u,v=minEdge
    visited.append(v)
    edges.append((u,v,minCost))
    cost+=minCost

  print("MST: ")
  for u,v,w in edges:
    print(f"{u}-{w}={v}")
  print("Total cost: ",cost)