# -*- coding: utf-8 -*-
"""selectionSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I_DsmPh9bco1xST6VastIWcmfEPCWyiW
"""

def selectionSort(arr):
  n=len(arr)

  for i in range(n):
    minIdx=i

    for j in range(i+1,n):
      if arr[j]<arr[minIdx]:
        minIdx=j

    arr[i],arr[minIdx]=arr[minIdx],arr[i]
  return arr

arr=[12,2,45,7,67,56,89,76]
selectionSort(arr)